spring.application.name=Springboot-API-REST

# Usar BD en memoria (H2) para que no necesites MySQL
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Esto evita que pida usuario/password
spring.datasource.username=sa
spring.datasource.password=