server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Ejemplo de configuración profesional
    location /api/v1/ventas/ {
    # 'backend-service' es el nombre que le das al servicio en ECS
    proxy_pass http://backend-ventas.local:8080/;
}

    # Proxy para Despachos
    location /api/v1/despachos {
        proxy_pass http://alb-innovatech-588814069.us-east-1.elb.amazonaws.com;
    }
}