spring.application.name=Springboot-API-REST
server.port=8081
spring.web.allow-cors=true

# --- CONFIGURACIÓN H2 (BASE DE DATOS EN MEMORIA) ---
spring.datasource.url=jdbc:h2:mem:despachosdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=sa
spring.datasource.password=

# --- SWAGGER ---
springdoc.swagger-ui.path=/swagger-ui.html