name: CI Pipeline - Build Only

on:
  push:
    branches: [ deploy ]
    paths:
      - 'proyecto semestral/front_despacho/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t frontend-innovatech:latest "./proyecto semestral/front_despacho"
          echo "Build completado exitosamente"